# Generated by Django 2.2.7 on 2019-11-25 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191124_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.PositiveSmallIntegerField(choices=[(2, 'thriller'), (0, 'undefined'), (3, 'drama'), (1, 'comedy'), (5, 'sci-fi'), (4, 'horror')])),
                ('duration', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='extra_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ExtraInfo'),
        ),
    ]
