# Generated by Django 2.2.7 on 2019-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191126_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(3, 'drama'), (1, 'comedy'), (5, 'sci-fi'), (0, 'undefined'), (2, 'thriller'), (4, 'horror')]),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('movie', models.ManyToManyField(to='api.Movie')),
            ],
        ),
    ]
