# Generated by Django 2.2.7 on 2019-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191126_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='movie',
            new_name='movies',
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'thriller'), (3, 'drama'), (0, 'undefined'), (4, 'horror'), (5, 'sci-fi'), (1, 'comedy')]),
        ),
    ]
